spring.application.name=terst-redis-project1


spring.docker.compose.lifecycle-management=start-only

spring.data.redis.cluster.nodes=localhost:7010,localhost:7011,localhost:7012,localhost:7013,localhost:7014,localhost:7015
spring.data.redis.cluster.max-redirects=5
spring.data.redis.timeout=5s
spring.data.redis.connect-timeout=5s
spring.data.redis.repositories.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?options=-c%20timezone=UTC
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.flyway.enabled=true
